#!/bin/bash
#PBS -q default 
#PBS -N sync
#PBS -l select=1:mem=60gb:ncpus=16
#PBS -l walltime=02:00:00
#PBS -j oe
#PBS -W group_list=x-ccast-prj-tseaborn 

source /mmfs1/scratch/rhiannon.hall/bee_samples/08_UMGC/BOGR/BIP/myenv/bin/activate 

mkdir -p /mmfs1/scratch/rhiannon.hall/bee_samples/08_UMGC/BOGR/BIP/myenv/BOGR/sync

for infile in /mmfs1/scratch/rhiannon.hall/bee_samples/08_UMGC/BOGR/BIP/myenv/BOGR/trim/*_R1_001.trim.fastq.gz

do 
    base=$(basename ${infile} _R1_001.trim.fastq.gz)

perl /mmfs1/scratch/rhiannon.hall/bee_samples/08_UMGC/BOGR/BIP/myenv/BOGR/scr/resync.pl ${infile} /mmfs1/scratch/rhiannon.hall/bee_samples/08_UMGC/BOGR/BIP/myenv/BOGR/trim/${base}_R2_001.trim.fastq.gz /mmfs1/scratch/rhiannon.hall/bee_samples/08_UMGC/BOGR/BIP/myenv/BOGR/sync/${base}_R1_synced.fastq /mmfs1/scratch/rhiannon.hall/bee_samples/08_UMGC/BOGR/BIP/myenv/BOGR/sync/${base}_R2_synced.fastq

done 

deactivate